[package]
name = "async-ssh2-lite-demo-smol"
version = "0.1.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2021"

[[bin]]
name = "proxy_jump"
path = "src/proxy_jump.rs"

[dependencies]
async-ssh2-lite = { path = "../..", version = "0.3", features = ["async-io"] }
futures = "0.3"
async-io = "1.3"
async-executor = "1.4"
easy-parallel = "3.1"
async-channel = "1.5"
tempfile = "3.1"
cfg-if = "1.0"
